[phases.setup]
nixPkgs = ['nodejs_18', 'python3']

[phases.install]
cmds = [
  'npm cache clean --force',
  'rm -rf node_modules package-lock.json',
  'npm install --legacy-peer-deps'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NODE_OPTIONS = '--max_old_space_size=3072'
NPM_CONFIG_PRODUCTION = 'false' 