name: Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - '**/*.{js,jsx,ts,tsx}'
      - 'package*.json'
      - '.github/workflows/build.yml'
      - 'nixpacks.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: System information
        run: |
          free -h
          df -h
          node --version
          npm --version

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci --prefer-offline --no-audit --maxsockets 1

      - name: Build
        run: |
          # Clear any cached data
          rm -rf .next
          # Run build with increased heap size and additional flags
          NEXT_TELEMETRY_DISABLED=1 node --trace-deprecation --max-old-space-size=8192 node_modules/.bin/next build
        env:
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          NODE_OPTIONS: "--max_old_space_size=8192 --no-warnings --expose-gc"
          NEXT_TELEMETRY_DISABLED: "1"
          NPM_CONFIG_PRODUCTION: "false"
          NODE_ENV: "production"
          CI: "true"
          NEXT_TURBO: "1"
